language: c

before_install:
    - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
    - sudo apt-get update

install:
    - sudo apt-get install build-essential
    - sudo apt-get install gcc-multilib
    - sudo apt-get install gcc-arm-embedded
    - sudo apt-get install g++-multilib

script:
    - make

notifications:
    email: false


